# Generated by Django 3.1.1 on 2020-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='hackKovid/images')),
                ('UploadToHINTLatestProductOrTOPSellingProducts', models.CharField(max_length=20)),
            ],
        ),
    ]
