# Generated by Django 3.1.1 on 2020-09-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackKovid', '0004_auto_20200926_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default='', max_length=20),
        ),
    ]
